// react-web/src/Home/index.js
import React, { Component } from 'react';
import moment from 'moment';
import './style.scss';
import Banner from './components/Banner';
import Category from './components/Category';
import ListCard from '../components/ListCard';
import MLink from '../components/MLink';
import HomeHeader from './components/HomeHeader';

const guides = [
  {
    title: '爆料站',
    iconName: 'news'
  },
  {
    title: '故事站',
    iconName: 'story'
  },
  {
    title: '周边商场',
    iconName: 'store'
  },
  {
    title: '体验服',
    iconName: 'beta'
  },
  {
    title: '新人专区',
    iconName: 'xrzq'
  },
  {
    title: '荣耀·传承',
    iconName: 'whz'
  },
  {
    title: '模拟战资料库',
    iconName: 'trz'
  },
  {
    title: '王者营地',
    iconName: 'wzyd'
  },
  {
    title: '公众号',
    iconName: 'wx'
  },
  {
    title: '版本介绍',
    iconName: 'version'
  }
]

const newsList = [{"name":"热门","newsList":[{"_id":"5e2529e8b3deac5f5023024f","categories":[{"_id":"5e2529c54b82750fc435164f","name":"赛事","parent":"5e25299c4b82750fc435164b","__v":0},{"_id":"5e2529b24b82750fc435164d","name":"公告","parent":"5e25299c4b82750fc435164b","__v":0}],"title":"新春王者翼起嗨 千店齐发线下开黑","__v":0,"createdAt":"2020-01-20T04:17:44.059Z","updatedAt":"2020-01-20T13:48:51.612Z","content":"<p><strong>老亚瑟发现1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题。</strong><strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong>。</p><p>问题说明：<strong style=\"color: rgb(255, 0, 0);\">1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题</strong></p><p>当前状态：<strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong></p><p>&nbsp;</p><p>我们对给各位召唤师造成影响感到非常非常的抱歉，给各位召唤师们带来的不便还请谅解，我们将在官网和其他官方平台为您及时更新处理进度。</p>","categoryName":"赛事"},{"_id":"5e2529e8b3deac5f50230250","categories":[{"_id":"5e2529b24b82750fc435164d","name":"公告","parent":"5e25299c4b82750fc435164b","__v":0},{"_id":"5e2529c54b82750fc435164f","name":"赛事","parent":"5e25299c4b82750fc435164b","__v":0}],"title":"峡谷英雄辞旧岁，快手集结迎新年","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T16:07:11.095Z","content":"<p>亲爱的召唤师：</p><p>&nbsp;&nbsp;&nbsp;全新活动玩法-觉醒之战将于版本更新后同步开启，关于玩法的详细介绍<a href=\"http://pvp.qq.com/m/m201606/newCont.shtml?G_Biz=18&amp;tid=438384\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(0, 0, 0);\">&gt;&gt;点击这里&lt;&lt;</a>查看。</p>","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230251","categories":[{"_id":"5e2529b24b82750fc435164d","name":"公告","parent":"5e25299c4b82750fc435164b","__v":0},{"_id":"5e2529a44b82750fc435164c","name":"新闻","parent":"5e25299c4b82750fc435164b","__v":0}],"title":"觉醒之战——斗鱼主播带你嗨翻天","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.060Z","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230252","categories":[{"_id":"5e2529a44b82750fc435164c","name":"新闻","parent":"5e25299c4b82750fc435164b","__v":0},{"_id":"5e2529be4b82750fc435164e","name":"活动","parent":"5e25299c4b82750fc435164b","__v":0}],"title":"年兽入侵丨那个神秘生物来了！搅乱峡谷的竟是它？！","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"新闻"},{"_id":"5e2529e8b3deac5f50230253","categories":[{"_id":"5e2529a44b82750fc435164c","name":"新闻","parent":"5e25299c4b82750fc435164b","__v":0},{"_id":"5e2529b24b82750fc435164d","name":"公告","parent":"5e25299c4b82750fc435164b","__v":0}],"title":"屈臣氏联合王者荣耀，打造新年游戏购物新体验","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"新闻"}]},{"_id":"5e2529a44b82750fc435164c","name":"新闻","parent":"5e25299c4b82750fc435164b","__v":0,"newsList":[{"_id":"5e2529e8b3deac5f50230251","categories":["5e2529b24b82750fc435164d","5e2529a44b82750fc435164c"],"title":"觉醒之战——斗鱼主播带你嗨翻天","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.060Z","categoryName":"新闻"},{"_id":"5e2529e8b3deac5f50230252","categories":["5e2529a44b82750fc435164c","5e2529be4b82750fc435164e"],"title":"年兽入侵丨那个神秘生物来了！搅乱峡谷的竟是它？！","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"新闻"},{"_id":"5e2529e8b3deac5f50230253","categories":["5e2529a44b82750fc435164c","5e2529b24b82750fc435164d"],"title":"屈臣氏联合王者荣耀，打造新年游戏购物新体验","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"新闻"},{"_id":"5e2529e8b3deac5f50230255","categories":["5e2529a44b82750fc435164c","5e2529b24b82750fc435164d"],"title":"李白-凤求凰个人主页展示异常问题说明","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"新闻"},{"_id":"5e2529e8b3deac5f50230256","categories":["5e2529a44b82750fc435164c","5e2529b24b82750fc435164d"],"title":"1月16日全服不停机更新公告","__v":0,"createdAt":"2020-01-20T04:17:44.062Z","updatedAt":"2020-01-20T04:17:44.062Z","categoryName":"新闻"}]},{"_id":"5e2529b24b82750fc435164d","name":"公告","parent":"5e25299c4b82750fc435164b","__v":0,"newsList":[{"_id":"5e2529e8b3deac5f5023024f","categories":["5e2529c54b82750fc435164f","5e2529b24b82750fc435164d"],"title":"新春王者翼起嗨 千店齐发线下开黑","__v":0,"createdAt":"2020-01-20T04:17:44.059Z","updatedAt":"2020-01-20T13:48:51.612Z","content":"<p><strong>老亚瑟发现1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题。</strong><strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong>。</p><p>问题说明：<strong style=\"color: rgb(255, 0, 0);\">1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题</strong></p><p>当前状态：<strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong></p><p>&nbsp;</p><p>我们对给各位召唤师造成影响感到非常非常的抱歉，给各位召唤师们带来的不便还请谅解，我们将在官网和其他官方平台为您及时更新处理进度。</p>","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230250","categories":["5e2529b24b82750fc435164d","5e2529c54b82750fc435164f"],"title":"峡谷英雄辞旧岁，快手集结迎新年","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T16:07:11.095Z","content":"<p>亲爱的召唤师：</p><p>&nbsp;&nbsp;&nbsp;全新活动玩法-觉醒之战将于版本更新后同步开启，关于玩法的详细介绍<a href=\"http://pvp.qq.com/m/m201606/newCont.shtml?G_Biz=18&amp;tid=438384\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(0, 0, 0);\">&gt;&gt;点击这里&lt;&lt;</a>查看。</p>","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230251","categories":["5e2529b24b82750fc435164d","5e2529a44b82750fc435164c"],"title":"觉醒之战——斗鱼主播带你嗨翻天","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.060Z","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230253","categories":["5e2529a44b82750fc435164c","5e2529b24b82750fc435164d"],"title":"屈臣氏联合王者荣耀，打造新年游戏购物新体验","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"公告"},{"_id":"5e2529e8b3deac5f50230254","categories":["5e2529b24b82750fc435164d","5e2529be4b82750fc435164e"],"title":"嬴政小头像不显示问题说明","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"公告"}]},{"_id":"5e2529be4b82750fc435164e","name":"活动","parent":"5e25299c4b82750fc435164b","__v":0,"newsList":[{"_id":"5e2529e8b3deac5f50230252","categories":["5e2529a44b82750fc435164c","5e2529be4b82750fc435164e"],"title":"年兽入侵丨那个神秘生物来了！搅乱峡谷的竟是它？！","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"活动"},{"_id":"5e2529e8b3deac5f50230254","categories":["5e2529b24b82750fc435164d","5e2529be4b82750fc435164e"],"title":"嬴政小头像不显示问题说明","__v":0,"createdAt":"2020-01-20T04:17:44.061Z","updatedAt":"2020-01-20T04:17:44.061Z","categoryName":"活动"},{"_id":"5e2529e8b3deac5f5023025b","categories":["5e2529be4b82750fc435164e","5e2529c54b82750fc435164f"],"title":"【觉醒英雄，赢精彩豪礼】活动开启公告","__v":0,"createdAt":"2020-01-20T04:17:44.063Z","updatedAt":"2020-01-20T04:17:44.063Z","categoryName":"活动"},{"_id":"5e2529e8b3deac5f5023025c","categories":["5e2529c54b82750fc435164f","5e2529be4b82750fc435164e"],"title":"娜可露露首套史诗皮肤-晚萤即将上架 更多礼遇等你解锁！","__v":0,"createdAt":"2020-01-20T04:17:44.063Z","updatedAt":"2020-01-20T04:17:44.063Z","categoryName":"活动"},{"_id":"5e2529e8b3deac5f5023025d","categories":["5e2529a44b82750fc435164c","5e2529be4b82750fc435164e"],"title":"探秘玄雍活动 参与拿专属好礼","__v":0,"createdAt":"2020-01-20T04:17:44.063Z","updatedAt":"2020-01-20T04:17:44.063Z","categoryName":"活动"}]},{"_id":"5e2529c54b82750fc435164f","name":"赛事","parent":"5e25299c4b82750fc435164b","__v":0,"newsList":[{"_id":"5e2529e8b3deac5f5023024f","categories":["5e2529c54b82750fc435164f","5e2529b24b82750fc435164d"],"title":"新春王者翼起嗨 千店齐发线下开黑","__v":0,"createdAt":"2020-01-20T04:17:44.059Z","updatedAt":"2020-01-20T13:48:51.612Z","content":"<p><strong>老亚瑟发现1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题。</strong><strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong>。</p><p>问题说明：<strong style=\"color: rgb(255, 0, 0);\">1月16日版本更新后，嬴政小头像（包含其皮肤头像）出现不显示的问题</strong></p><p>当前状态：<strong style=\"color: rgb(255, 0, 0);\">目前问题正在紧急定位中</strong></p><p>&nbsp;</p><p>我们对给各位召唤师造成影响感到非常非常的抱歉，给各位召唤师们带来的不便还请谅解，我们将在官网和其他官方平台为您及时更新处理进度。</p>","categoryName":"赛事"},{"_id":"5e2529e8b3deac5f50230250","categories":["5e2529b24b82750fc435164d","5e2529c54b82750fc435164f"],"title":"峡谷英雄辞旧岁，快手集结迎新年","__v":0,"createdAt":"2020-01-20T04:17:44.060Z","updatedAt":"2020-01-20T16:07:11.095Z","content":"<p>亲爱的召唤师：</p><p>&nbsp;&nbsp;&nbsp;全新活动玩法-觉醒之战将于版本更新后同步开启，关于玩法的详细介绍<a href=\"http://pvp.qq.com/m/m201606/newCont.shtml?G_Biz=18&amp;tid=438384\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(0, 0, 0);\">&gt;&gt;点击这里&lt;&lt;</a>查看。</p>","categoryName":"赛事"},{"_id":"5e2529e8b3deac5f50230259","categories":["5e2529a44b82750fc435164c","5e2529c54b82750fc435164f"],"title":"凤求凰&amp;凤凰于飞限时返场 皮肤优化即将来袭","__v":0,"createdAt":"2020-01-20T04:17:44.062Z","updatedAt":"2020-01-20T04:17:44.062Z","categoryName":"赛事"},{"_id":"5e2529e8b3deac5f5023025b","categories":["5e2529be4b82750fc435164e","5e2529c54b82750fc435164f"],"title":"【觉醒英雄，赢精彩豪礼】活动开启公告","__v":0,"createdAt":"2020-01-20T04:17:44.063Z","updatedAt":"2020-01-20T04:17:44.063Z","categoryName":"赛事"},{"_id":"5e2529e8b3deac5f5023025c","categories":["5e2529c54b82750fc435164f","5e2529be4b82750fc435164e"],"title":"娜可露露首套史诗皮肤-晚萤即将上架 更多礼遇等你解锁！","__v":0,"createdAt":"2020-01-20T04:17:44.063Z","updatedAt":"2020-01-20T04:17:44.063Z","categoryName":"赛事"}]}]

// 新闻列表插槽
const newsSlot = function (category, index) {
  return (
    <ul key={index} className="w-100 swiper-slide">
      {
        category.newsList.map((item) => {
          return (
            <MLink
              key={item._id}
              tag='li'
              to={`/articles/${item._id}`}
              className="py-2 fs-lg flex-row">
              <span className="text-info">[{item.categoryName}]</span>
              <span className="px-2">|</span>
              <span className="flex-1 text-dark-1 text-ellipsis pr-2">{item.title}</span>
              <span className="text-dark fs-sm">{moment(item.createdAt).format('MM/DD')}</span>
            </MLink>
          )
        })
      }
    </ul>
  )
}

// 英雄列表插槽
const heroSlot = function (hero, i) {
  return (
    <ul key={hero._id} className="flex-row flex-wrap" style={{margin: '0 -0.5rem'}}>
      {
        hero.heroList.map((item) => {
          return (<MLink
            tag="li"
            key={item._id}
            to={`/hero/${item._id}`}
            className="p-2 text-center"
            style={{'width': '20%'}}>
            <div className='heroAvatar'>
              <img className="heroAvatar__img" alt="" src={item.avatar}/>
            </div>
            <div>{item.name}</div>
          </MLink>)
        })
      }
    </ul>
  );
}

class Home extends Component {
  render() {
    return (
      <React.Fragment>
        <HomeHeader></HomeHeader>
        <Banner data={[1, 2, 3]}></Banner>
        <Category data={guides}></Category>
        <ListCard categories={newsList} title="新闻资讯" slot={newsSlot} swiperName='news-swiper'></ListCard>
        <ListCard title="英雄列表" icon="hero" swiperName='hero-swiper' slot={heroSlot}></ListCard>
      </React.Fragment>
    );
  }
}

export default Home;

// web/src/views/Home/index.vue
<template>
  <div>
    <swiper v-if="homeAds" :options="swiperOtions">
      <swiper-slide v-for="item in homeAds.items" :key="item._id">
        <a :href="item.url">
          <img class="w-100" :src="item.image" alt="">
        </a>
      </swiper-slide>
      <div class="swiper-pagination pagination-home text-right px-3 pb-1" slot="pagination"></div>
    </swiper>
    <!-- end of swiper -->
    <div class="nav-icons bg-white mt-3 text-center pt-3 text-grey-1">
      <ul class="flex-row flex-wrap ai-center">
        <li class="nav-item mb-3" v-for="item in guides" :key="item.iconName">
          <i :class="['sprite', 'sprite-' + item.iconName]"></i>
          <div class="py-2">{{item.title}}</div>
        </li>
      </ul>
      <div class="bg-light py-2 fs-sm">
        <i class="sprite sprite-around mr-1"></i>
        <span>收起</span>
      </div>
    </div>
    <!-- end of icons -->

    <m-list-card title="新闻资讯" icon="menu" :categories="newsCats">
      <template #items="{ category }">
        <ul>
          <router-link
            v-for="(item, i) in category.newsList"
            :key="i"
            class="py-2 fs-lg flex-row"
            tag="li"
            :to="{ name: 'articles', params: {id: item._id} }">
            <span class="text-info">[{{item.categoryName}}]</span>
            <span class="px-2">|</span>
            <span class="flex-1 text-dark-1 text-ellipsis pr-2">{{item.title}}</span>
            <span class="text-dark fs-sm">{{item.createdAt | date}}</span>
          </router-link>
        </ul>
      </template>
    </m-list-card>

    <m-list-card title="英雄列表" icon="hero" :categories="heroCats">
      <template #items="{ category }">
        <ul class="flex-row flex-wrap" style="margin: 0 -0.5rem;">
          <router-link
            tag="li"
            v-for="(item, i) in category.heroList" :key="i"
            :to="{ name: 'hero', params: { id: item._id } }"
            style="width: 20%;"
            class="p-2 text-center">
            <img :src="item.avatar" class="w-100" alt="">
            <div>{{item.name}}</div>
          </router-link>
        </ul>
      </template>
    </m-list-card>
    <!-- <m-card title="精彩视频" icon="video"></m-card>
    <m-card title="图文攻略" icon="article"></m-card> -->
  </div>
</template>

<script>
import moment from 'moment' // dayjs
export default {
  data () {
    return {
      swiperOtions: {
        pagination: {
          el: '.swiper-pagination'
        }
      },
      // 导航
      guides: [
        {
          title: '爆料站',
          iconName: 'news'
        },
        {
          title: '故事站',
          iconName: 'story'
        },
        {
          title: '周边商场',
          iconName: 'store'
        },
        {
          title: '体验服',
          iconName: 'beta'
        },
        {
          title: '新人专区',
          iconName: 'xrzq'
        },
        {
          title: '荣耀·传承',
          iconName: 'whz'
        },
        {
          title: '模拟战资料库',
          iconName: 'trz'
        },
        {
          title: '王者营地',
          iconName: 'wzyd'
        },
        {
          title: '公众号',
          iconName: 'wx'
        },
        {
          title: '版本介绍',
          iconName: 'version'
        }
      ],
      newsCats: [],
      heroCats: [],
      homeAds: null
    }
  },
  methods: {
    async fetchNewsList () {
      const res = await this.$http.get('/news/list')
      this.newsCats = res.data
    },
    async fetchHeroList () {
      const res = await this.$http.get('/heroes/list')
      this.heroCats = res.data
    },
    // 获取首页幻灯片
    async fetchAds () {
      const res = await this.$http.get('/ads/home')
      this.homeAds = res.data
    }
  },
  created() {
    this.fetchNewsList()
    this.fetchHeroList()
  },
  filters: {
    date(val) {
      return moment(val).format('MM/DD')
    }
  }
}
</script>

<style lang="scss">
  @import '../../assets/css/variables';
  .pagination-home {
    .swiper-pagination-bullet {
      opacity: 1;
      border-radius: .153846rem /* 2/13 */;
      background: map-get($map: $colors, $key: 'white');
      &.swiper-pagination-bullet-active {
        background: map-get($map: $colors, $key: 'info');
      }
    }
  }

  .nav-icons {
    border-top: 1px solid $border-color;
    border-bottom: 1px solid $border-color;
    .nav-item {
      width: 25%;
      border-left: 1px solid $border-color;
      &:nth-child(4n + 1) {
        border-color: transparent;
      }
    }
  }

  .sprite-version {
    background: url(../../assets/images/version-icon.png) no-repeat 0 0;
    background-size: 1.538462rem /* 20/13 */;
    width: 1.615385rem /* 21/13 */;
    height: 1.846154rem /* 24/13 */;
  }

</style>
