// react-web/src/containers/Hero/index.js
import React, { Component } from 'react';
import Card from '../../components/Card';
import { Link } from 'react-router-dom';
import Logo from '../../assets/logo.png';
import HeroTop from './components/HeroTop';
import Partner from './components/Partner';
import Items from './components/Items';
import MLink from '../../components/MLink';
import MSwiper from '../../components/MSwiper';

const model = {"_id":"5e2565c777676935e0df5f07","categories":[{"_id":"5e25643be9d22c4d00cab11d","name":"战士","parent":"5e25642ee9d22c4d00cab11c","__v":0}],"items1":[{"_id":"5ea44e79d7cecc43ef2381e8","name":"兰德里的折磨","icon":"http://www.hypermoba.xyz/uploads/5b5568da851d00c0ec64108bb5f2a2fe","__v":0}],"items2":[{"_id":"5ea44e54d7cecc43ef2381e7","name":"饮血刀","icon":"http://www.hypermoba.xyz/uploads/48c651b88c2c1ea83f498616d17c2f18","__v":0}],"name":"赵云","avatar":"https://game.gtimg.cn/images/yxzj/img201606/heroimg/107/107.jpg","skills":[],"partners":[],"__v":0,"banner":"http://www.hypermoba.xyz/uploads/7102ca10cb078342125a7c4f96c0e267","scores":{"diffcult":7,"skills":6,"attack":6,"survive":6},"title":"大傻逼","battleTips":"冲冲冲","teamTips":"冲冲冲","usageTips":"冲冲冲"};

const introduceHeroRender = (data) => (
  <React.Fragment>
    <div className="p-3 bg-white border-bottom">
      <div className="flex-row">
        <MLink tag="button" to="/" className="btn btn-lg flex-1">
          <i className="iconfont icon-video"></i>
          英雄介绍视频
        </MLink>
        <MLink tag="button" to="/" className="btn btn-lg flex-1 ml-2">
          <i className="iconfont icon-image"></i>
          一图说英雄
        </MLink>
      </div>
    </div>
    <Card plain={true} title="出装推荐">
      <Items items1={data.items1} items2={data.items2}></Items>
    </Card>
    <Card plain={true} title="使用技巧">
      <p className="m-0">{data.usageTips}</p>
    </Card>
    <Card plain={true} title="对抗技巧">
      <p className="m-0">{data.battleTips}</p>
    </Card>
    <Card plain={true} title="团战思路">
      <p className="m-0">{data.teamTips}</p>
    </Card>
    <Card plain={true} title="英雄关系">
      <Partner data={data.partners}></Partner>
    </Card>
  </React.Fragment>
);

class Hero extends Component {
  constructor (props) {
    super(props);
    this.state = {
      realIndex: 0 // 当前swiper
    };
  }
  render() {
    const { realIndex } = this.state;
    return (
      <div className="page-hero">
        <div className="topbar bg-black py-2 px-3 flex-row ai-center">
          <img src={Logo} alt="" height="30" />
          <div className="px-2 flex-1">
            <div className="text-white">王者荣耀</div>
            <span className="ml-2 text-white">攻略站</span>
          </div>
          <Link className="text-white" to="/" tag="div">更多英雄 &gt;</Link>
        </div>
        {/* end of top */}
        <HeroTop {...model}></HeroTop>
        <div>
          <div className="px-3 bg-white">
            <div className="nav flex-row py-2 jc-around border-bottom pt-3 pb-2">
              <div className={realIndex === 0 ? "nav-item active": "nav-item"} onClick={this.slide.bind(this, 0)}>
                <div className="nav-link">英雄初识</div>
              </div>
              <div className={realIndex === 1 ? "nav-item active": "nav-item"} onClick={this.slide.bind(this, 1)}>
                <div className="nav-link">进阶攻略</div>
              </div>
            </div>
          </div>
          <MSwiper
            slideChange={this.slide}
            index={realIndex}
            swiperName="heroDetail-swiper"
            slotArray={[introduceHeroRender(model), null]}></MSwiper>
        </div>
      </div>
    );
  }
  slide = (index) => {
    this.setState({
      realIndex: index
    });
  }
}

export default Hero;

// web/src/views/Hero/index.vue
<template>
  <div class="page-hero" v-if="model">
    <div class="topbar bg-black py-2 px-3 flex-row ai-center">
      <img src="../../assets/logo.png" height="30" alt="">
      <div class="px-2 flex-1">
        <div class="text-white">王者荣耀</div>
        <span class="ml-2">攻略站</span>
      </div>
      <router-link class="text-white" to="/" tag="div">更多英雄 &gt;</router-link>
    </div>
    <div class="top" :style="{backgroundImage: `url(${model.banner})`}">
      <div class="info text-white p-3 flex-column h-100 jc-end">
        <div class="fs-sm">{{model.title}}</div>
        <h2 class="my-2">{{model.name}}</h2>
        <div class="fs-sm">{{model.categories.map(v => v.name).join('/')}}</div>
        <div class="flex-row jc-between ai-center">
          <div class="scores flex-row ai-center pt-2" v-if="model.scores">
            <span>难度</span>
            <span class="badge bg-primary">{{model.scores.diffcult}}</span>
            <span>技能</span>
            <span class="badge bg-blue-1">{{model.scores.skills}}</span>
            <span>攻击</span>
            <span class="badge bg-danger">{{model.scores.attack}}</span>
            <span>生存</span>
            <span class="badge bg-dark">{{model.scores.survive}}</span>
          </div>
          <router-link tag="span" class="text-grey fs-sm" to="/">皮肤: 2 &gt;</router-link>
        </div>
      </div>
    </div>
    <!-- end of top -->
    <div>
      <div class="px-3 bg-white">
        <div class="nav flex-row py-2 jc-around border-bottom pt-3 pb-2">
          <div class="nav-item active">
            <div class="nav-link">英雄初识</div>
          </div>
          <div class="nav-item">
            <div class="nav-link">进阶攻略</div>
          </div>
        </div>
      </div>
      <swiper>
        <swiper-slide>
          <div>
            <div>
              <div class="p-3 bg-white border-bottom">
                <div class="flex-row">
                  <router-link tag="button" to="/" class="btn btn-lg flex-1">
                    <i class="iconfont icon-video"></i>
                    英雄介绍视频
                  </router-link>
                  <router-link tag="button" to="/" class="btn btn-lg flex-1 ml-2">
                    <i class="iconfont icon-image"></i>
                    一图说英雄
                  </router-link>
                </div>

                <!-- skills -->
                <div class="skills bg-white mt-4">
                  <div class="flex-row jc-around">
                    <img
                      v-for="(item, i) in model.skills"
                      :key="item.name"
                      class="icon"
                      :class="{ 'active': currentSkillIndex === i }"
                      @click="currentSkillIndex = i"
                      :src="item.icon"
                      alt="">
                  </div>
                  <div v-if="currentSkill">
                    <div class="flex-row py-4">
                      <h3 class="m-0">{{currentSkill.name}}</h3>
                      <span class="text-grey-1 ml-4">
                        冷却值：{{currentSkill.delay}} 消耗：{{currentSkill.cost}}
                      </span>
                    </div>
                    <p>{{currentSkill.description}}</p>
                    <div class="border-bottom"></div>
                    <p class="text-grey-1 fs-sm">小提示：{{currentSkill.tips}}</p>
                  </div>
                </div>
              </div>
              <m-card plain icon="menu" title="出装推荐" class="hero-items">
                <div class="fs-xl">顺风出装</div>
                <div class="flex-row jc-around text-center mt-3">
                  <div v-for="item in model.items1" :key="item.name" >
                    <img class="icon" :src="item.icon" :key="item.icon" alt="">
                    <div class="fs-xs">{{item.name}}</div>
                  </div>
                </div>
                <div class="border-bottom mt-3"></div>
                <div class="fs-xl mt-3">逆风出装</div>
                <div class="flex-row jc-around text-center mt-3">
                  <div v-for="item in model.items2" :key="item.name" >
                    <img class="icon" :src="item.icon" :key="item.icon" alt="">
                    <div class="fs-xs">{{item.name}}</div>
                  </div>
                </div>
              </m-card>
              <m-card plain icon="menu" title="使用技巧">
                <p class="m-0">{{model.usageTips}}</p>
              </m-card>
              <m-card plain icon="menu" title="对抗技巧">
                <p class="m-0">{{model.battleTips}}</p>
              </m-card>
              <m-card plain icon="menu" title="团战思路">
                <p class="m-0">{{model.teamTips}}</p>
              </m-card>
              <m-card plain icon="menu" title="英雄关系">
                <dl>
                  <dt class="fs-xl">最佳搭档</dt>
                  <dd v-for="item in model.partners" :key="item._id" class="flex-row pt-3">
                    <img :src="item.hero.avatar" :key="item._id" height="50" alt="">
                    <p class="flex-1 my-0 ml-3">{{item.description}}</p>
                  </dd>
                </dl>
              </m-card>
            </div>
          </div>
        </swiper-slide>
        <swiper-slide>
          <div></div>
        </swiper-slide>
      </swiper>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    id: {
      required: true
    }
  },
  data () {
    return {
      model: null,
      currentSkillIndex: 0
    }
  },
  computed: {
    currentSkill () {
      if (this.model) {
        return this.model.skills[this.currentSkillIndex]
      }
      return null
    }
  },
  created() {
    if (this.id) {
      this.fetch()
    }
  },
  methods: {
    async fetch () {
      const res = await this.$http.get(`/heroes/${this.id}`)
      this.model = res.data
    } 
  }
}
</script>

<style lang="scss" scoped>
@import '../../assets/css/variables.scss';
.page-hero {
  .top {
    height: 50vw;
    background: #fff no-repeat top center;
    background-size: auto 100%;
  }
  .info {
    background: linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 1));
    .scores {
      .badge {
        margin: 0 0.25rem;
        display: inline-block;
        width: 1rem;
        height: 1rem;
        text-align: center;
        line-height: .9rem;
        border-radius: 50%;
        font-size: .75rem;
        border: 1px solid rgba($color: #fff, $alpha: .2);
      }
    }
  }

  .skills {
    img.icon {
      width: 5.385rem /* 70/13 */;
      height: 5.385rem /* 70/13 */;
      border: .231rem /* 3/13 */ solid map-get($map: $colors, $key: 'white');
      &.active {
        border-color: map-get($map: $colors, $key: 'primary');
      }
      border-radius: 50%;
    }
  }

  .hero-items {
    img.icon {
      width: 45px;
      height: 45px;
      border-radius: 50%;
    }
  }
}
</style>
