// web/src/components/ListCard.vue
<template>
  <m-card title="新闻资讯" icon="menu">
    <ul class="nav flex-row jc-between">
      <li
        v-for="(category, index) in categories"
        :key="index" class="nav-item"
        :class="{'active': activeIndex === index}"
        @click="activeIndex = index">
        <div class="nav-link">{{category.name}}</div>
      </li>
    </ul>
    <div class="pt-3">
      <swiper>
        <swiper-slide v-for="(category, i) in categories" :key="i">
          <slot name="items" :category="category"></slot>
        </swiper-slide>
      </swiper>
    </div>
  </m-card>
</template>

<script>
export default {
  props: {
    title: {
      type: String,
      required: true
    },
    icon: {
      type: String,
      required: true
    },
    categories: {
      type: Array,
      required: true
    }
  },
  data () {
    return {
      activeIndex: 0
    }
  }
}
</script>

<style lang="scss" scoped>
  
</style>

// react-web/src/components/ListCard/index.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import MSwiper from '../MSwiper';
import Card from '../Card';

class ListCard extends Component {
  constructor (props) {
    super(props);
    this.state = {
      activeIndex: 0
    }
  }
  render() {
    const { title, icon, categories, slot, swiperName } = this.props;
    const { activeIndex } = this.state;
    return (
      <Card title={title} icon={icon}>
        <ul className="nav flex-row jc-between">
          {
            categories.map((category, i) => {
              return (
                <li key={i} className={activeIndex === i ? 'nav-item active': 'nav-item'} onClick={this.switchCategory.bind(this, i)}>
                  <div className="nav-link">{category.name}</div>
                </li>
              )
            })
          }
        </ul>
        <div className="pt-3" style={{boxSizing: 'border-box'}}>
          <MSwiper
            swiperName={swiperName}
            slideChange={this.switchCategory}
            index={activeIndex}
            slotArray={
              categories.map((category, i) => {
                return (slot ? slot(category, i) : null);
              })
            }></MSwiper>
        </div>
      </Card>
    );
  }
  // 切换分类
  switchCategory = (index) => {
    this.setState({
      activeIndex: index
    })
  }
}

ListCard.propTypes = {
  title: PropTypes.string.isRequired,
  icon: PropTypes.string.isRequired,
  categories: PropTypes.array.isRequired,
  swiperName: PropTypes.string
}

ListCard.defaultProps = {
  title: '',
  icon: 'menu',
  categories: [],
  swiperName: 'listCard-swiper'
}

export default ListCard;
