// web/src/views/Article/index.vue
<template>
  <div class="page-article" v-if="model">
    <div class="flex-row py-3 px-2 border-bottom">
      <div class="iconfont icon-back text-blue"></div>
      <strong class="flex-1 text-blue">{{model.title}}</strong>
      <div class="text-grey fs-sm">{{model.createdAt}}</div>
    </div>
    <div v-html="model.content" class="px-3 article-body fs-lg"></div>
    <div class="px-3 py-3 border-top">
      <div class="flex-row ai-center">
        <i class="iconfont icon-article"></i>
        <strong class="text-blue ml-2 fs-lg">相关资讯</strong>
      </div>
      <div class="pt-2">
        <router-link v-for="item in model.related" :key="item._id" tag="div"
          class="py-2 mt-2"
          :to="{ name: 'articles', params: { id: item._id } }">
          {{item.title}}
        </router-link>
      </div>
    </div>
  </div>
</template>

<script>
import moment from 'moment'
export default {
  props: {
    id: {
      required: true
    }
  },
  data () {
    return {
      model: null
    }
  },
  created() {
    this.fetchArticle()
  },
  methods: {
    async fetchArticle () {
      const res = await this.$http.get(`/articles/${this.id}`)
      this.model = res.data
    }
  },
  watch: {
    id: 'fetchArticle'
  },
  filters: {
    formatDate (val) {
      return moment(val).format('YYYY-MM-DD')
    }
  }
}
</script>

<style lang="scss">
  .page-article {
    .icon-back {
      font-size: 1.692308rem /* 22/13 */;
    }
    .article-body {
      img {
        max-width: 100%;
        height: auto;
      }
      iframe {
        width: 100%;
        height: auto;
      }
    }
  }

</style>

// react-web/src/containers/Article/index.js
import React, { Component } from 'react';
import moment from 'moment';
import './style.scss';
import MLink from '../../components/MLink';
import { connect } from 'react-redux';
import { actions as articleAction, getArticleById } from '../../redux/modules/article';
import { bindActionCreators } from 'redux';

class Article extends Component {
  render() {
    const { article } = this.props;
    if (article) {
      return (
        <React.Fragment>
          <div className="page-article">
            <div className="flex-row py-3 px-2 border-bottom">
              <div className="iconfont icon-back text-blue"></div>
              <strong className="flex-1 text-blue">{article.title}</strong>
              <div className="text-grey fs-sm">{moment(article.createdAt).format('YYYY-MM-DD')}</div>
            </div>
            <div className="px-3 article-body fs-lg" dangerouslySetInnerHTML={{ __html: article.content }}></div>
            <div className="px-3 py-3 border-top">
              <div className="flex-row ai-center">
                <i className="iconfont icon-article"></i>
                <strong className="text-blue ml-2 fs-lg">相关资讯</strong>
              </div>
              <div className="pt-2">
                {
                  article.related.map((item) => {
                    return (
                      <MLink
                        key={item._id}
                        to={`/articles/${item._id}`}
                        className="py-2 mt-2">{item.title}</MLink>
                    )
                  })
                }
              </div>
            </div>
          </div>
        </React.Fragment>
      );
    } else {
      return null;
    }
  }
  componentDidMount () {
    const { article } = this.props;
    if (!article) {
      const id = this.props.match.params.id;
      this.props.articleAction.loadArticleInfo(id);
    }
  }
}

const mapStateToProps = (state, props) => {
  const id = props.match.params.id;
  return {
    article: getArticleById(state, id)
  };
};

const mapDispatchToProps = dispatch => {
  return {
    articleAction: bindActionCreators(articleAction, dispatch)
  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Article);
